### ISSUE TITLE
Why systemd is removed

### ISSUE THREAD

**Issue by alpana17** [behance/docker-base#55]
I was going through the dockerfiles and found that s6 s installed and systemd is removed https://github.com/behance/docker-base/blob/master/Dockerfile-ubuntu-18.04#L31

Why systemd is removed.
How one will manage services like enabling/disabling some service etc.?

**Comment by bryanlatten** [comment]
Hi @alpana17! systemd is a tremendous (and awesome) subsystem for running services on hosts.
We remove it for a few reasons:
- It has a huge footprint and security surface, removing eliminates that [vector](https://cve.mitre.org/cgi-bin/cvekey.cgi?keyword=systemd)
- Small containers = faster deployments = faster scaling operations
- Attempt to not recreate VM's inside containers: running complex services may be the exception, not the rule

S6 is extremely lightweight, and enables you to run one or more processes within your container. Please see base docs [here](https://github.com/behance/docker-base#expectations), and S6 docs [here](https://github.com/just-containers/s6-overlay#writing-a-service-script).

**Comment by bryanlatten** [comment]
I'm going close this issue @alpana17 (there is no action), feel free to reopen or create another!
